In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print("2 dimensional array:",b)

2 dimensional array: [[1 2 3 4]
 [5 6 7 8]]


In [3]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
d=np.random.random((3,3))
print(d)

[[0.89907028 0.33695022 0.12971028]
 [0.27931147 0.07833303 0.2472593 ]
 [0.03424717 0.83137761 0.27101504]]


In [6]:
e=np.arrange(0,30,5)
print(e)

AttributeError: module 'numpy' has no attribute 'arrange'

In [2]:
e=np.arange(0,30,5)
print(e)

NameError: name 'np' is not defined

In [5]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [6]:
import numpy as np
flat=arr.flatten()
print(arr)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [7]:
print(arr.ndim)

2


In [8]:
print(arr.shape)

(3, 4)


In [9]:
print(arr.dtype)

int64


In [10]:
print(arr.size)

12


In [12]:
newtype=arr.astype('f')
print("\n convert array:\n",newtype)
print("\n convert array:\n",newtype.dtype)


 convert array:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 0. 1.]]

 convert array:
 float32


In [13]:
size=len(arr)
print("\n sixe of array:\n",size)


 sixe of array:
 3
